version: '3.5'

services:
  projeto42-sonarqube:
    image: ${DOCKER_REGISTRY}projeto42/sonarqube:${TAG}-ci
    container_name: ${CONTAINER_NAME:-ci-tests-artifacts}
    build:
      context: .
      dockerfile: src/Projeto42.SonarQube.WebApi/Dockerfile
      target: tests
    environment:
      RUN_SONARQUBE: ${RUN_SONARQUBE}
      SONARQUBE_URL: ${SONARQUBE_URL}
      SONARQUBE_TOKEN: ${SONARQUBE_TOKEN}
      SONARQUBE_PROJECT: ${SONARQUBE_PROJECT}
      SONARQUBE_PROJECT_VERSION: ${SONARQUBE_PROJECT_VERSION}